packages:
  - apps/*
  - packages/*
  - "@acme/**"
  - "!@acme/frameworks"

catalog:
  # t3-turbo
  "@tanstack/react-query": ^5.62.16
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.17.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.16
  typescript: ^5.7.2
  zod: ^3.24.1
  # more
  # date-fns: ^4.1.0
  # zustand: "^5.0.2"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.3
    "@types/react-dom": ^19.0.2
