packages:
  - apps/*
  - '!apps/macos'
  - '@acme/*'
  - packages/*
  - '!packages/claude-plugins'

catalog:
  '@eslint/js': ^10.0.1
  '@hookform/resolvers': 5.2.2
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/vite': ^4.2.1
  '@tanstack/react-query': ^5.90.21
  '@testing-library/react': ^16.3.2
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@trpc/tanstack-react-query': ^11.10.0
  '@types/lodash': ^4.17.24
  '@types/node': ^25.3.1
  ahooks: ^3.9.6
  colorjs.io: ^0.6.1
  date-fns: 'catalog:'
  dayjs: ^1.11.19
  eslint: ^10.0.2
  jsdom: ^28.1.0
  lodash: ^4.17.21
  lucide-react: 0.577.0
  next-themes: 'catalog:'
  prettier: ^3.8.1
  react-hook-form: 7.71.2
  tailwindcss: ^4.2.1
  type-fest: ^5.4.3
  typescript: ^5.9.3
  usehooks-ts: ^3.1.1
  uuid: ^13.0.0
  vite: ^7.3.1
  zod: 4.3.6
  zustand: ^5.0.11

catalogs:
  react19:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

onlyBuiltDependencies:
  - bufferutil
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - supabase

patchedDependencies:
  radix-ui@1.4.3: patches/radix-ui@1.4.3.patch
