packages:
  - '*'

catalog:
  '@eslint/js': ^9.39.1
  '@hookform/resolvers': ^5.2.2
  "@tailwindcss/postcss": ^4.1.14
  "@tailwindcss/vite": ^4.1.14
  '@tanstack/react-query': ^5.90.2
  '@trpc/client': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/lodash': ^4.17.20
  '@types/node': ^24.10.0
  dayjs: ^1.11.19
  eslint: ^9.39.1
  lucide-react: ^0.555.0
  next-themes: ^0.4.6
  prettier: ^3.6.2
  react-hook-form: ^7.66.0
  tailwindcss: ^4.1.16
  type-fest: ^5.2.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  zod: ^4.1.12
  zustand: ^5.0.8

catalogs:
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - core-js-pure
